/**
 * Manage persisted custom project-container folders.
 *
 * POST accepts the absolute directory returned by Electron's native folder
 * picker. The server validates and stores it; later project routes accept only
 * the opaque root id generated by project-roots.ts, never arbitrary paths.
 */

import crypto from "node:crypto";
import { NextResponse } from "next/server";
import { isWorkspaceConnected } from "../../../server/connected-store";
import {
  addProjectRoot,
  getProjectRoots,
  removeProjectRoot,
} from "../../../server/project-roots";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function hasValidPickerCapability(request: Request): boolean {
  const expected = process.env.BLUBBER_PICKER_TOKEN;
  const provided = request.headers.get("x-blubber-picker-token");
  if (!expected || !provided) return false;
  const expectedBytes = Buffer.from(expected);
  const providedBytes = Buffer.from(provided);
  return expectedBytes.length === providedBytes.length && crypto.timingSafeEqual(expectedBytes, providedBytes);
}

export async function GET() {
  // Preserve the same fresh-install privacy boundary as /api/projects: do not
  // expose the local username through absolute default paths before consent.
  const roots = getProjectRoots();
  if (!isWorkspaceConnected()) {
    return NextResponse.json({ roots: roots.filter((root) => root.custom) });
  }
  return NextResponse.json({ roots });
}

export async function POST(request: Request) {
  if (!hasValidPickerCapability(request)) {
    return NextResponse.json({ ok: false, error: "folder picker authorization required" }, { status: 403 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ ok: false, error: "invalid JSON" }, { status: 400 });
  }

  if (!body || typeof body !== "object" || typeof (body as { path?: unknown }).path !== "string") {
    return NextResponse.json({ ok: false, error: "path must be a string" }, { status: 400 });
  }

  const result = addProjectRoot((body as { path: string }).path);
  return NextResponse.json(result, { status: result.ok ? 200 : 400 });
}

export async function DELETE(request: Request) {
  const id = new URL(request.url).searchParams.get("id") ?? "";
  if (!id) return NextResponse.json({ ok: false, error: "missing root id" }, { status: 400 });
  if (!removeProjectRoot(id)) {
    return NextResponse.json({ ok: false, error: "custom project folder not found" }, { status: 404 });
  }
  return NextResponse.json({ ok: true });
}
